server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_springboot_backend?serverTimezone=America/Mexico_City
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: debug