insert into clientes (nombre,apellido,email,create_at) values('david','Saldivar','david@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Jose','Sandoval','jose@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Andrea','Guzman','andrea@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Erika','Garza','erika@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Daniel','Cantu','daniel@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Fernando','Rodriguez','fer@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Carlos','Tellez','carlos@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Ana','Dominguez','ana@client.com','2019-12-22');
insert into clientes (nombre,apellido,email,create_at) values('Sonia','Beltran','sonia@client.com','2019-12-22');